// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.motorcontrol.MotorControllerGroup;
import edu.wpi.first.wpilibj.motorcontrol.PWMTalonFX;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Drive extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private PWMTalonFX lFront;
    private PWMTalonFX lBack;
    private MotorControllerGroup leftMotors;
    private PWMTalonFX rFront;
    private PWMTalonFX rBack;
    private MotorControllerGroup rightMotors;
    private DifferentialDrive differentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /**
    *
    */
    public Drive() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        lFront = new PWMTalonFX(1);
        addChild("lFront", lFront);
        lFront.setInverted(false);

        lBack = new PWMTalonFX(2);
        addChild("lBack", lBack);
        lBack.setInverted(false);

        leftMotors = new MotorControllerGroup(lFront, lBack);
        addChild("LeftMotors", leftMotors);

        rFront = new PWMTalonFX(3);
        addChild("rFront", rFront);
        rFront.setInverted(false);

        rBack = new PWMTalonFX(4);
        addChild("rBack", rBack);
        rBack.setInverted(false);

        rightMotors = new MotorControllerGroup(rFront, rBack);
        addChild("RightMotors", rightMotors);

        differentialDrive = new DifferentialDrive(leftMotors, rightMotors);
        addChild("DifferentialDrive", differentialDrive);
        differentialDrive.setSafetyEnabled(true);
        differentialDrive.setExpiration(0.1);
        differentialDrive.setMaxOutput(1.0);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    /**
     * Cheesy driving for the drivetrain.
     * 
     * @param speed      robot Speed from [-1.0..1.0]
     * @param curvature  robot turn radius from [-1.0..1.0]
     * @param isSpinning whether or not the robot is spinning in place
     */
    public void drive(double speed, double curvature, boolean isSpinning) {
        differentialDrive.curvatureDrive(speed, curvature, isSpinning);
    }

}
